### ISSUE TITLE
Unable to find expected entry 'main/binary-i386/Packages' in Release file

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/install.enclave.io#10]
Following installation [instructions for Ubuntu](https://docs.enclave.io/getting-started/installation/) apt reports that there is no `i386` package for Enclave (`apt-get update`).

```
W: Failed to fetch https://packages.enclave.io/apt/dists/unstable/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
```
 
```
root@asterisk:/# uname -a
Linux asterisk 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 
```
root@asterisk:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
```

**Comment by enclave-marc-barry** [comment]
`i386` lost from `ARCHS` variable in [this commit](https://github.com/enclave-networks/container.deb-repo/commit/290c080fc592e3efe0c2fccb254a1b59301dbf19)

**Comment by enclave-marc-barry** [comment]
Alistair has updated [freight.conf](https://github.com/enclave-networks/container.deb-repo/commit/54863ccee7049b77025c95ed0f093370a7894ef7) to include `i386` however I notice the [current artifacts from the latest build on](http://vm-win2016-build.enclave:8080/buildConfiguration/enclave_fabric_linux/3828?buildTab=artifacts) of master do not include an x86 binary.

**Comment by enclave-marc-barry** [comment]
This did indeed break the release pipeline without i386 binaries feeding in. I'll revert the change, we'll need to start from the other end of the pipeline and ensure teamcity is producing x86 binaries..

**Comment by enclave-marc-barry** [comment]
Let's close this issue for now and wait for a *paying* customer to flag this to us again in the future.

**Comment by enclave-marc-barry** [comment]
Marc: test this on asterisk box to confirm APT works if we uninstall and reinstall.

**Comment by enclave-marc-barry** [comment]
apt was defaulting to `i386` architecture packages despite being an `x86_64` processor (`uname -a`, or `amd64` if you ask `dpkg --print-architecture`)

to install the 64 bit version of the package I was able to force apt: `apt-get install enclave:amd64`

**Comment by enclave-marc-barry** [comment]
I've "documented" the i386 workaround on our [community forum](https://community.enclave.io/t/apt-get-install-enclave-fails-to-fetch-main-binary-i386-packages/30/2) and raise a separate [issue](https://github.com/enclave-networks/install.enclave.io/issues/11) to track officially supporting i386 architectures.

**Comment by enclave-marc-barry** [comment]
Something is still not right here.

According to `ec2-status` this asterisk Linux server (`Q88X8`) is running `enclave/2021.2.3.561`.

It's also running on `stable` channel. After last night's GA I've just logged on to try and update it. This is what happened.

1. Remind myself how enclave got onto this host in the first place: https://community.enclave.io/t/apt-get-install-fails-to-fetch-main-binary-i386-packages/30

```
apt-get install enclave:amd64
```

2. Use the Enclave connection between my laptop and this server to SSH in and check the channel apt is using

```bash
root@asterisk:~# cat /etc/apt/sources.list.d/enclave.stable.list
deb https://packages.enclave.io/apt stable main
```

3. Update apt

```bash
root@asterisk:~# apt-get update
Ign http://apt.newrelic.com newrelic InRelease
Hit http://apt.newrelic.com newrelic Release.gpg
Hit http://apt.newrelic.com newrelic Release
Hit http://apt.newrelic.com newrelic/non-free amd64 Packages
Ign http://mirrors.digitalocean.com trusty InRelease
Hit http://apt.newrelic.com newrelic/non-free i386 Packages
Hit http://mirrors.digitalocean.com trusty-updates InRelease
Hit http://mirrors.digitalocean.com trusty-backports InRelease
Hit http://mirrors.digitalocean.com trusty-security InRelease
Hit http://mirrors.digitalocean.com trusty Release.gpg
Hit http://mirrors.digitalocean.com trusty-updates/main Sources
Hit http://mirrors.digitalocean.com trusty-updates/restricted Sources
Ign http://apt.newrelic.com newrelic/non-free Translation-en_US
Ign http://apt.newrelic.com newrelic/non-free Translation-en
Hit http://mirrors.digitalocean.com trusty-updates/universe Sources
Hit http://mirrors.digitalocean.com trusty-updates/multiverse Sources
Hit http://mirrors.digitalocean.com trusty-updates/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty-updates/restricted amd64 Packages
Hit http://mirrors.digitalocean.com trusty-updates/universe amd64 Packages
Hit http://mirrors.digitalocean.com trusty-updates/multiverse amd64 Packages
Hit http://mirrors.digitalocean.com trusty-updates/main i386 Packages
Hit http://mirrors.digitalocean.com trusty-updates/restricted i386 Packages
Hit http://mirrors.digitalocean.com trusty-updates/universe i386 Packages
Hit http://mirrors.digitalocean.com trusty-updates/multiverse i386 Packages
Hit http://mirrors.digitalocean.com trusty-updates/main Translation-en
Hit http://mirrors.digitalocean.com trusty-updates/multiverse Translation-en
Hit http://mirrors.digitalocean.com trusty-updates/restricted Translation-en
Hit https://download.mono-project.com stable-trusty InRelease
Hit http://mirrors.digitalocean.com trusty-updates/universe Translation-en
Hit http://mirrors.digitalocean.com trusty Release
Hit http://mirrors.digitalocean.com trusty-backports/main Sources
Hit http://mirrors.digitalocean.com trusty-backports/restricted Sources
Hit http://mirrors.digitalocean.com trusty-backports/universe Sources
Hit http://mirrors.digitalocean.com trusty-backports/multiverse Sources
Hit http://mirrors.digitalocean.com trusty-backports/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty-backports/restricted amd64 Packages
Hit http://mirrors.digitalocean.com trusty-backports/universe amd64 Packages
Hit http://mirrors.digitalocean.com trusty-backports/multiverse amd64 Packages
Hit http://mirrors.digitalocean.com trusty-backports/main i386 Packages
Hit http://mirrors.digitalocean.com trusty-backports/restricted i386 Packages
Hit http://mirrors.digitalocean.com trusty-backports/universe i386 Packages
Hit http://mirrors.digitalocean.com trusty-backports/multiverse i386 Packages
Hit http://mirrors.digitalocean.com trusty-backports/main Translation-en
Hit https://download.mono-project.com stable-trusty/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty-backports/multiverse Translation-en
Hit http://mirrors.digitalocean.com trusty-backports/restricted Translation-en
Hit http://mirrors.digitalocean.com trusty-backports/universe Translation-en
Hit http://mirrors.digitalocean.com trusty-security/main Sources
Hit http://mirrors.digitalocean.com trusty-security/restricted Sources
Hit http://mirrors.digitalocean.com trusty-security/universe Sources
Hit http://mirrors.digitalocean.com trusty-security/multiverse Sources
Hit http://mirrors.digitalocean.com trusty-security/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty-security/restricted amd64 Packages
Hit http://mirrors.digitalocean.com trusty-security/universe amd64 Packages
Hit http://mirrors.digitalocean.com trusty-security/multiverse amd64 Packages
Hit http://mirrors.digitalocean.com trusty-security/main i386 Packages
Hit http://mirrors.digitalocean.com trusty-security/restricted i386 Packages
Hit http://mirrors.digitalocean.com trusty-security/universe i386 Packages
Hit https://packages.enclave.io stable InRelease
Hit http://mirrors.digitalocean.com trusty-security/multiverse i386 Packages
Hit http://mirrors.digitalocean.com trusty-security/main Translation-en
Hit https://download.mono-project.com stable-trusty/main i386 Packages
Hit http://mirrors.digitalocean.com trusty-security/multiverse Translation-en
Hit https://packages.enclave.io stable/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty-security/restricted Translation-en
Hit http://mirrors.digitalocean.com trusty-security/universe Translation-en
Hit http://mirrors.digitalocean.com trusty/main Sources
Hit http://mirrors.digitalocean.com trusty/restricted Sources
Hit http://mirrors.digitalocean.com trusty/universe Sources
Hit http://mirrors.digitalocean.com trusty/multiverse Sources
Hit http://mirrors.digitalocean.com trusty/main amd64 Packages
Hit http://mirrors.digitalocean.com trusty/restricted amd64 Packages
Hit http://mirrors.digitalocean.com trusty/universe amd64 Packages
Hit http://mirrors.digitalocean.com trusty/multiverse amd64 Packages
Hit http://mirrors.digitalocean.com trusty/main i386 Packages
Hit http://mirrors.digitalocean.com trusty/restricted i386 Packages
Hit http://mirrors.digitalocean.com trusty/universe i386 Packages
Hit http://mirrors.digitalocean.com trusty/multiverse i386 Packages
Hit http://mirrors.digitalocean.com trusty/main Translation-en
Hit http://mirrors.digitalocean.com trusty/multiverse Translation-en
Hit http://mirrors.digitalocean.com trusty/restricted Translation-en
Hit http://mirrors.digitalocean.com trusty/universe Translation-en
Ign http://mirrors.digitalocean.com trusty/main Translation-en_US
Ign http://mirrors.digitalocean.com trusty/multiverse Translation-en_US
Ign http://mirrors.digitalocean.com trusty/restricted Translation-en_US
Ign http://mirrors.digitalocean.com trusty/universe Translation-en_US
Ign https://download.mono-project.com stable-trusty/main Translation-en_US
Ign https://download.mono-project.com stable-trusty/main Translation-en
W: Failed to fetch https://packages.enclave.io/apt/dists/stable/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

4. Ok... let's try and install again.

```bash
root@asterisk:~# sudo apt-get install enclave:amd64
Reading package lists... Done
Building dependency tree... 50%
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libmpdec2 libwireshark3 libwiretap3 libwsutil3
Use 'apt-get autoremove' to remove them.
The following packages will be upgraded:
  enclave
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 26.9 MB of archives.
After this operation, 100 kB of additional disk space will be used.
0% [Working]

Fetched 26.9 MB in 1s (15.7 MB/s)
(Reading database ... 109822 files and directories currently installed.)
Preparing to unpack .../enclave_2021.06.16.705_amd64.deb ...
Unpacking enclave (2021.06.16.705) over (2021.05.12.677) ...
Setting up enclave (2021.06.16.705) ...
Failed to issue method call: No such file or directory
Failed to issue method call: Unit enclave.service failed to load: No such file or directory. See system logs and 'systemctl status enclave.service' for details.
```

5. Not great. Lets look at the service status

```bash
root@asterisk:~# systemctl status enclave.service
enclave.service
   Loaded: error (Reason: No such file or directory)
   Active: active (running) since Wed 2021-04-14 16:45:44 UTC; 2 months 2 days ago
 Main PID: 20379 (enclave)
```

6. Ok, so what the heck version of Enclave are we running on now then to support this SSH channel? (presumably the old version - `enclave/2021.2.3.561`, right?)

```
root@asterisk:~# enclave version
enclave-linux-x64 2021.06.16.705
```

7. Ok, so if we just run the newly dropped binary we expect it perhaps to tell us IT's version, not the version running. Let's use the `status` verb to check what version is *actually* running..

```
root@asterisk:~# enclave status

Local identity: Q88X8

   Release version . . : 2021.6.16.705
   Profile name. . . . : Universe
   Profile location. . : /etc/enclave/profiles/Universe.profile
   Certificate . . . . : CN=Q88X8 Expires=Never (Perpetual Issue)
   Binding address . . : 0.0.0.0:50285
   Local nameserver. . : listening on 100.70.14.78:53
   Local adapter . . . : tap0 (#21) 2E:D5:FA:00:41:05
   Local address . . . : 100.70.14.78
   Local network . . . : 100.64.0.0/10 (255.192.0.0)
Object reference not set to an instance of an object.
```

**Comment by enclave-alistair** [comment]
I'm guessing that the running fabric process is the old version, but the exe that runs when you call `enclave status` is the new version.

If the existing service doesn't stop before it updates, it will keep running the old binary (from the extracted .net bundle location most likely). It would explain the null-ref.

The `enclave status` command doesn't actually report the version of the fabric, it reports the version of the executing binary (possibly unwise).

**Comment by enclave-marc-barry** [comment]
> The enclave status command doesn't actually report the version of the fabric, it reports the version of the executing binary (possibly unwise).

agreed, we should fix.

I'm still unclear how the enclave repo is breaking `apt-get update` and yet I managed to install enclave on this host using apt.

**Comment by enclave-alistair** [comment]
What's in the enclave apt source file?

**Comment by enclave-marc-barry** [comment]
```
root@asterisk:~# cat /etc/apt/sources.list.d/enclave.stable.list
deb https://packages.enclave.io/apt stable main
```

**Comment by enclave-alistair** [comment]
Hmm; unsure. It's possible it's to do with it being a 14.04 system having slightly different systemd behaviour? 

Not to be "that guy", but I'll point out that Ubuntu 14.04 reached end-of-life in 2019, so I'm reluctant to put much time into investigating this if it can't be replicated on a 16.04 system.

**Comment by enclave-marc-barry** [comment]
Too late :) 

Would you mind having a look at https://unix.stackexchange.com/questions/272908/apt-looking-for-i386-files-even-though-architecture-is-amd64 and see if you think there's any action we should take on our repo?

**Comment by enclave-marc-barry** [comment]
I've fixed the apt-get update issue by adding the arch directive to the sources file

```
root@asterisk:~# cat /etc/apt/sources.list.d/enclave.stable.list
deb [arch=amd64] https://packages.enclave.io/apt stable main
```

Until we publish i386, and because of the default amd64 behaviour, we ought to update our install instructions?

**Comment by enclave-alistair** [comment]
But this issue doesn't occur on any other amd64 systems apart from this one.  We install to amd64 linux boxes all the time.

**Comment by enclave-alistair** [comment]
Also worth noting that stackexchange question is from 2016.

**Comment by enclave-alistair** [comment]
Related: https://superuser.com/a/714392/42736

**Comment by enclave-marc-barry** [comment]
Ta. To me this is about being explicit in our deb package install instructions that we're only publishing amd64 architecture packages. Some older systems, in lieu of explicit specifications may assume we publish more than we do - I think we should add `[arch=amd64]` to the sources file and move on - it won't cause issues going forwards until we add support for i386 and will mean anybody (like me) running some older systems can deploy without headaches

**Comment by enclave-alistair** [comment]
Have you by any chance explicitly added i386 support to `dpkg` on your server at some point? As opposed to it being a default situation (i.e. `dpkg --print-foreign-architectures`). 

Perhaps to run an old piece of software?

Note that we will never support i386 with enclave in it's current form; .net core does not support it.

**Comment by enclave-alistair** [comment]
Also, disagree on adding it to our default instructions; our repo also hosts `arm` and `armhf` variants, and we don't want to have to give raspberry pi users a choice of which architecture they're on, when the whole point of apt is to figure it out automatically.

We can document somewhere what you should do if you've got i386 architectures enabled on an amd64 system, and leave it at that.

**Comment by enclave-marc-barry** [comment]
> Have you by any chance explicitly added i386 support to `dpkg` on your server at some point? As opposed to it being a default situation (i.e. `dpkg --print-foreign-architectures`).
> 
> Perhaps to run an old piece of software?
> 
> Note that we will never support i386 with enclave in it's current form; .net core does not support it.

100% never (knowingly)

**Comment by enclave-marc-barry** [comment]
> Also, disagree on adding it to our default instructions; our repo also hosts `arm` and `armhf` variants, and we don't want to have to give raspberry pi users a choice of which architecture they're on, when the whole point of apt is to figure it out automatically.
> 
> We can document somewhere what you should do if you've got i386 architectures enabled on an amd64 system, and leave it at that.

Okay, you're right
