### ISSUE TITLE
Review setup.sh script fix to DOTNET_BUNDLE_EXTRACT_BASE_DIR to service file

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/install.enclave.io#13]
Review PR https://github.com/enclave-networks/install.enclave.io/pull/12

> Is it really okay to define DOTNET_BUNDLE_EXTRACT_BASE_DIR for the service in this way? I've hard coded the TMP path (because on testing, CentOS doesn't seem to have a variable telling us where to find the TMP directory). Without a deeper look at the documentation I'm not sure how this variable is scoped either, we don't want to override the location of DOTNET_BUNDLE_EXTRACT_BASE_DIR if it's been set by the user.
> 
> In the interests of making this work short term I'm going to merge this PR and raise an issue to sanity check the change post-merge.

**Comment by enclave-alistair** [comment]
Any environment variables defined in this file only apply to the process launched by the service, so there's no issuing setting `DOTNET_BUNDLE_EXTRACT_BASE_DIR` here.

In the main apt package we specify this value as `%h/.net/enclave`, which expands to the user home directory.

@enclave-marc-barry, did CentOS testing indicate that the `%h` replacement variable does not work on CentOS? I believed it to be a general systemd feature.

**Comment by enclave-marc-barry** [comment]
Interesting. I didn't try. Will pick this up.
