### ISSUE TITLE
Update `setup.sh` script to prefer RPM where available

### ISSUE THREAD

**Issue by enclave-alistair** [enclave-networks/install.enclave.io#16]
Our current `setup.sh` script looks for `apt`, and if it's there, installs Enclave from our repository. 

We should do the same thing for RPM-compatible distros.

**Comment by bcronje** [comment]
Just keep in mind the issue around older rpm based distros like CentOS 7 that does not support rpm v5.x

```
[bcronje@centos-dev tmp]$ rpm -i enclave-2022.05.30.373-1.x86_64.rpm 
error: Failed dependencies:
	rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by enclave-2022.05.30.373-1.fc35.x86_64
```

**Comment by enclave-alistair** [comment]
Ah, good shout, we'll need to take that into consideration.
