### ISSUE TITLE
Enclave errors during install on Amazon Linux 2

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/install.enclave.io#22]
1. Enclave errors during install on Amazon Linux 2 (see below)
2. We have no uninstall instructions for hosts where Enclave has been installed using `setup.sh` and need some

## Steps to Reproduce

It looks like this error may have been introduced with [this commit](https://github.com/enclave-networks/install.enclave.io/commit/d7ac0660beffc5bd378882496a5fbd4ceec0a7d4)

Spin up a new Amazon Linux 2 virtual machine on AWS LightSail

![image](https://user-images.githubusercontent.com/67782240/235142284-92acd350-001f-4b70-a0a2-e5238ddef77d.png)

Install Enclave using `setup.sh` via `bash <(curl -Ss https://install.enclave.io/setup.sh)`

![image](https://user-images.githubusercontent.com/67782240/235142718-5f2e1633-593e-4ea0-81de-675a50943898.png)

Notice the error

```bash
[ec2-user@ip-172-26-2-141 ~]$ bash <(curl -Ss https://install.enclave.io/setup.sh)
[+] Checking/installing dependencies.
/dev/fd/63: line 40: [[: %{fedora}: syntax error: operand expected (error token is "%{fedora}")
[-] Unsupported distro detected. Some dependencies may not be present.
[+] Installing enclave-2023.4.25.1108.
[-] No enrolment key supplied.
[-] Enclave requires an enrolment key in order to request a certificate and enrol this system into your account.
Enter enrolment key:
```

## Expected behaviour

No error or warning messages during installation.

**Comment by enclave-marc-barry** [comment]
Is our uninstall manual script as simple as this?

```
sudo rm -rf /usr/bin/enclave
sudo rm -rf /usr/lib/systemd/system/enclave.service
sudo rm -rf /usr/lib/systemd/user/enclave-auth.service
sudo rm -rf /usr/share/doc/enclave
sudo rm -rf /root/.net/enclave
```

Or do we also need to reload any services like `systemd` following the delete?

**Comment by ghost** [comment]
we probably want to unregister the systemd service first but that's not far of

**Comment by enclave-marc-barry** [comment]
Thanks @enclave-tom, are you able to help complete the steps for manual uninstall and add to docs?

**Comment by enclave-alistair** [comment]
@enclave-tom; anything documentation-wise need doing here as per Marc's comment?

**Comment by ghost** [comment]
closing this issue as the remaining issues are now tracked seperatly for better visibility
