### ISSUE TITLE
Add `--remove` option to the `setup.sh` script. 

### ISSUE THREAD

**Issue by ghost** [enclave-networks/install.enclave.io#24]
Our `setup.sh` script requires an option to remove the assocaited files it installs and files that are created by enclave.

This will look something like 
```
sudo rm -rf /usr/bin/enclave
sudo rm -rf /usr/lib/systemd/system/enclave.service
sudo rm -rf /usr/lib/systemd/user/enclave-auth.service
sudo rm -rf /usr/share/doc/enclave
sudo rm -rf /root/.net/enclave
```

As part of this we also need to document it's usage. 

Relates to https://github.com/enclave-networks/install.enclave.io/issues/22

**Comment by enclave-alistair** [comment]
This sounds eminently sensible; would we remove enclave installations deployed via the package manager (in the same way that we _install_ via the package manager if appropriate)?
